name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build || echo "sem build"

      - name: Zip APK (simulação)
        run: |
          mkdir -p artefatos
          echo "APK GERADO" > artefatos/app.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-apk
          path: artefatos/app.apk
